/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package at.rpisec.swagger.client.app.client.api;

import at.rpisec.swagger.client.app.client.invoker.ApiCallback;
import at.rpisec.swagger.client.app.client.invoker.ApiClient;
import at.rpisec.swagger.client.app.client.invoker.ApiException;
import at.rpisec.swagger.client.app.client.invoker.ApiResponse;
import at.rpisec.swagger.client.app.client.invoker.Configuration;
import at.rpisec.swagger.client.app.client.invoker.Pair;
import at.rpisec.swagger.client.app.client.invoker.ProgressRequestBody;
import at.rpisec.swagger.client.app.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class InternalRestControllerApi {
    private ApiClient apiClient;

    public InternalRestControllerApi() {
        this(Configuration.getDefaultApiClient());
    }

    public InternalRestControllerApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /* Build call for registerClientUsingPOST */
    private com.squareup.okhttp.Call registerClientUsingPOSTCall(String deviceId, Long userId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/internal/register".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (deviceId != null)
        localVarFormParams.put("deviceId", deviceId);
        if (userId != null)
        localVarFormParams.put("userId", userId);

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call registerClientUsingPOSTValidateBeforeCall(String deviceId, Long userId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'deviceId' is set
        if (deviceId == null) {
            throw new ApiException("Missing the required parameter 'deviceId' when calling registerClientUsingPOST(Async)");
        }
        
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling registerClientUsingPOST(Async)");
        }
        
        
        com.squareup.okhttp.Call call = registerClientUsingPOSTCall(deviceId, userId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * registerClient
     * 
     * @param deviceId deviceId (required)
     * @param userId userId (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void registerClientUsingPOST(String deviceId, Long userId) throws ApiException {
        registerClientUsingPOSTWithHttpInfo(deviceId, userId);
    }

    /**
     * registerClient
     * 
     * @param deviceId deviceId (required)
     * @param userId userId (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> registerClientUsingPOSTWithHttpInfo(String deviceId, Long userId) throws ApiException {
        com.squareup.okhttp.Call call = registerClientUsingPOSTValidateBeforeCall(deviceId, userId, null, null);
        return apiClient.execute(call);
    }

    /**
     * registerClient (asynchronously)
     * 
     * @param deviceId deviceId (required)
     * @param userId userId (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call registerClientUsingPOSTAsync(String deviceId, Long userId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = registerClientUsingPOSTValidateBeforeCall(deviceId, userId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for registerFCMTokenUsingPOST */
    private com.squareup.okhttp.Call registerFCMTokenUsingPOSTCall(String deviceId, String fcmToken, Long userId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/internal/registerFcmToken".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (deviceId != null)
        localVarFormParams.put("deviceId", deviceId);
        if (fcmToken != null)
        localVarFormParams.put("fcmToken", fcmToken);
        if (userId != null)
        localVarFormParams.put("userId", userId);

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call registerFCMTokenUsingPOSTValidateBeforeCall(String deviceId, String fcmToken, Long userId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'deviceId' is set
        if (deviceId == null) {
            throw new ApiException("Missing the required parameter 'deviceId' when calling registerFCMTokenUsingPOST(Async)");
        }
        
        // verify the required parameter 'fcmToken' is set
        if (fcmToken == null) {
            throw new ApiException("Missing the required parameter 'fcmToken' when calling registerFCMTokenUsingPOST(Async)");
        }
        
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling registerFCMTokenUsingPOST(Async)");
        }
        
        
        com.squareup.okhttp.Call call = registerFCMTokenUsingPOSTCall(deviceId, fcmToken, userId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * registerFCMToken
     * 
     * @param deviceId deviceId (required)
     * @param fcmToken fcmToken (required)
     * @param userId userId (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void registerFCMTokenUsingPOST(String deviceId, String fcmToken, Long userId) throws ApiException {
        registerFCMTokenUsingPOSTWithHttpInfo(deviceId, fcmToken, userId);
    }

    /**
     * registerFCMToken
     * 
     * @param deviceId deviceId (required)
     * @param fcmToken fcmToken (required)
     * @param userId userId (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> registerFCMTokenUsingPOSTWithHttpInfo(String deviceId, String fcmToken, Long userId) throws ApiException {
        com.squareup.okhttp.Call call = registerFCMTokenUsingPOSTValidateBeforeCall(deviceId, fcmToken, userId, null, null);
        return apiClient.execute(call);
    }

    /**
     * registerFCMToken (asynchronously)
     * 
     * @param deviceId deviceId (required)
     * @param fcmToken fcmToken (required)
     * @param userId userId (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call registerFCMTokenUsingPOSTAsync(String deviceId, String fcmToken, Long userId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = registerFCMTokenUsingPOSTValidateBeforeCall(deviceId, fcmToken, userId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /* Build call for unregisterClientSUsingPOST */
    private com.squareup.okhttp.Call unregisterClientSUsingPOSTCall(List<String> deviceId, Long userId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/internal/unregister".replaceAll("\\{format\\}","json");

        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (deviceId != null)
        localVarFormParams.put("deviceId", deviceId);
        if (userId != null)
        localVarFormParams.put("userId", userId);

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] { "basicAuth" };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call unregisterClientSUsingPOSTValidateBeforeCall(List<String> deviceId, Long userId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'deviceId' is set
        if (deviceId == null) {
            throw new ApiException("Missing the required parameter 'deviceId' when calling unregisterClientSUsingPOST(Async)");
        }
        
        // verify the required parameter 'userId' is set
        if (userId == null) {
            throw new ApiException("Missing the required parameter 'userId' when calling unregisterClientSUsingPOST(Async)");
        }
        
        
        com.squareup.okhttp.Call call = unregisterClientSUsingPOSTCall(deviceId, userId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * unregisterClientS
     * 
     * @param deviceId deviceId (required)
     * @param userId userId (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void unregisterClientSUsingPOST(List<String> deviceId, Long userId) throws ApiException {
        unregisterClientSUsingPOSTWithHttpInfo(deviceId, userId);
    }

    /**
     * unregisterClientS
     * 
     * @param deviceId deviceId (required)
     * @param userId userId (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> unregisterClientSUsingPOSTWithHttpInfo(List<String> deviceId, Long userId) throws ApiException {
        com.squareup.okhttp.Call call = unregisterClientSUsingPOSTValidateBeforeCall(deviceId, userId, null, null);
        return apiClient.execute(call);
    }

    /**
     * unregisterClientS (asynchronously)
     * 
     * @param deviceId deviceId (required)
     * @param userId userId (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call unregisterClientSUsingPOSTAsync(List<String> deviceId, Long userId, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = unregisterClientSUsingPOSTValidateBeforeCall(deviceId, userId, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
}
