Spring Boot application
=======================
Thomas Herzog <herzog.thomas81@gmail.com>

This document describes the usage of this application and how to set it up in an development and productive environment.

# Description
The spring boot application provides the user management for the __rpisec__ applications. It handles the
firebase logins, stores the client devices __(client_id, client_secret)__ and registers the user client devices
on the __rpisec-app__ application.

# Setup
This section deals with the setup of the spring boot application. +
The application supports two profiles __dev__ and __prod__ where the __productive__
environment is hosted with a docker infrastructure and the __development__ environment
works as a standalone application with no special setup necessary.

## Externalized configuration
The configuration has been split to a static part which is packaged into the application
and a dynamic part which is provided via the configuration file  __oauth-external-application.properties__. +
An template for the configuration file __oauth-external-application.properties__
can be found link:../../host/config/oauth-external-application.properties[here]. +

Firebase needs a configuration file which must be kep private.

## Development Environment __(profile dev)__
This section deals with the necessary setup for the development environment.

### VM Options
[options="header"]
|======================
|Option                    | Values      | Usage
|-Dplatform                |  dev, prod  | Activates either dev or prod configurations
|-Dspring.config.location  | file:<path_to_file>/<config_file_name>.properties | Includes the externalized configuration
|-Dadmin.email             | <ADMIN_EMAIL> | The email address of the default created administrator. If not present when the administrator is tried to be created during startup then the startup will fail
|======================

### Externalized Configuration
The externalized configuration file can be named and located as intended and will be
defined via an VM option as mentioned in the former section.

### Firebase
The __oauth-external-application.properties__ file must contain the parameter __firebase.configFile__ which defines
the location and name of the firebase configuration file. +

## Productive Environment
This section deals with the necessary setup for the productive environment. +
The productive environment is hosted in a docker infrastructure which is defined
via a docker-compose.yml which can be found link:../../host/docker/docker-compose.yml[here]. +

The docker infrastructure requires the following environment variables which must be visible
to docker-compose and most of the variables are defined in the __.env__ file which can be found  link:../../host/docker/.env[here]. +

Mostly the volumes are defined int he __.env__ file which shall be located in the docker executing user's home.
[options="header"]
|==============================
| Variable             | Value                       | Usage                                                   | Location
| OAUTH_APP_VOLUME     | ~/docker-volumes/oauth/app  | mapped volume for the rpisec-oauth jars                 | .env
| OAUTH_CONF_VOLUME    | ~/docker-volumes/oauth/conf | mapped volume for the rpisec-oauth configuration        | .env
| OAUTH_LOG_VOLUME     | ~/docker-volumes/oauth/log  | mapped volume for the rpisec-oauth logs                 | .env
| OAUTH_DB_VOLUME      | ~/docker-volumes/oauth/db   | mapped volume for the rpisec-oauth database             | .env
| RPISEC_VERSION       | 0.0.1-SNAPSHOT              | the current version of the microservice infrastructure  | ~/.bashrc
|==============================

### Externalized Configuration
The externalized configuration file must be named __oauth-external-application.properties__
and must be located at the root of the mapped conf volume defined by the environment variable __OAUTH_CONF_VOLUME__.

### Firebase
The firebase configuration file must be named __firebase-account.json__ and must be located
at the root of the mapped conf volume defined by the environment variable __OAUTH_CONF_VOLUME__.

# REST-API
This section describes the rest api available to the clients. +

### [GET] /api/client/clientLogin?deviceId=myDeviceId
This api method performs a login for a client device and provides the token for the firebase login
as well as the __clientId__ and __clientSecret__ for the oauth api access. +

This api requires a Http BasicAuth with username and password of an registered user with an enabled user account.

.JSON response
[source,json]
---------------------------------------------------------------------
{
  "created": "06.06.2017 07:19:21",
  "token": "eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImV4cCI6MTQ5Njc3MzE2MSwiaWF0IjoxNDk2NzY5NTYxLCJpc3MiOiJmaXJlYmFzZS1hZG1pbnNkay1hODdzY0BycGlzZWMtODllMTUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJzdWIiOiJmaXJlYmFzZS1hZG1pbnNkay1hODdzY0BycGlzZWMtODllMTUuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCJ1aWQiOiIyYjU0NGYxZC02NTY2LTQ0ODMtOWQ4Ni1mNmY3NzAxMmFmYzEifQ.z5Oo1G6_zkGYZY5Z2liW_w6SRmAqCudxmbQy_8n35yePxWz6vK-9UlnRSFcd_gLlmx2EOXXA7TymeryU_0Lef4We_aLwxMJZJKApujMnzRiaIAB5wKYJtxADzRoAF-SC_Nbz2Ikf7v5LnRCENykaKnvudKONaWBdLmWhOJfdhQ8cWxRPq-OLgZZRAgcSK35ch7wXcLwXNFqZuebFIfeSLVWUokRmVlH6bi7D9cdeXs1knCQ1rq2HPxlFtT7zdVlNcy6yOQAfFIzqCyNkYvcUTkKzIqEy3vVRD8_Y9qQAIjxnYtVHpxujqBis_CPM5eenLZSQ5_AZqqNDLbtP0ZjywA",
  "clientId": "3a97bafe-8d2e-4f2e-bd01-14715bc17435",
  "clientSecret": "11c2216c-9d2d-4926-9892-94f8371ff5f4"
}
---------------------------------------------------------------------

### [PUT] /api/client/registerFcmToken?deviceId=myDeviceId&fcmToken=myToken
This api registers a firebase cloud messaging token for a client device, the app server will push notifications to. +

This api requires a Http BasicAuth with username and password of an registered user with an enabled user account
which has this client device assigned to him. +

This api does only return a response code _200_ in the case of a successful registration.
