FROM library/debian:jessie
MAINTAINER Thomas Herzog <herzog.thomas81@gmail.com>

RUN RUN apt-get update -y && \
    apt-get install -y oracle-java8-jdk \
    apt-get autoremove --purge -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*