Docker infrastructure
=====================
Thomas Herzog <herzog.thomas81@gmail.com>

This document describes the docker infrastructure which hosts the __rpisec__ related applications.

# Description
The docker images can only used on an ARM-architecture and are based on the base image
__ resin/rpi-raspbian:jessie__ where we provide an custom base image named __rpisec-rpisec-base__
which can be replaced to get the infrastructure running on an other architecture. +

The base image __rpisec-base__ defined in this link:./base/Dockerfile[Dockerfile] builds installs
the raspberry pi necessary binaries for interacting with the raspberry hardware and additionally the
arm based oracle jdk in version 8. +

The docker infrastructure is defined in the file link:./docker-compose.yml[docker-compose.yml].

# Services
This section deals with the docker-infrastructure hosted service.
[options="header"]
|======================
| Service name             | Usage
| rpisec-app               | The service hosting the __rpisec-app__ which hosts the sesnor application and pushes the notifications to the client devices interacts with the firebase database
| rpisec-app-db            | The service hosting the postgres database used by the __rpisec-app__ service
| rpisec-auth             | The service hosting the spring boot authentication server for authentication and user management
| rpisec-auth-db          | The service hosting the postgres database used by the __rpisec-auth__ service
| rpisec-nginx             | The service hosting the reverse proxy for accessing the __rpisec-app__ and __rpisec-auth__ services
|======================

# Configuration
This section deals with the configuration of the docker infrastructure. +
The __docker-compose.yml__ uses environment variables where most of them are provided via the link:./.env[.env] file.
The following tables shows the necessary environment variables, their usage and recommended location.

[options="header"]
|==============================
| Variable             | Value                       | Usage                                                   | Location
| APP_CONF_VOLUME      | ~/docker-volumes/app/conf   | mapped volume for the rpisec-app configurations         | .env
| APP_LOG_VOLUME       | ~/docker-volumes/app/log    | mapped volume for the rpisec-app logs                   | .env
| APP_IMAGE_VOLUME     | ~/docker-volumes/app/image  | mapped volume for the rpisec-app incident images        | .env
| APP_DB_VOLUME        | ~/docker-volumes/app/db     | mapped volume for the rpisec-app database               | .env
| AUTH_CONF_VOLUME    | ~/docker-volumes/auth/conf | mapped volume for the rpisec-auth configuration        | .env
| AUTH_LOG_VOLUME     | ~/docker-volumes/auth/log  | mapped volume for the rpisec-auth logs                 | .env
| AUTH_DB_VOLUME      | ~/docker-volumes/auth/db   | mapped volume for the rpisec-auth database             | .env
| NGINX_LOG_VOLUME     | ~/docker-volumes/nginx/logs | mapped volume for the nginx logs                        | .env
| NGINX_CERT_VOLUME    | ~/docker-volumes/nginx/cert | mapped volume for the nginx used certs                  | .env
| RPISEC_VERSION       | 0.0.1-SNAPSHOT              | the current version of the microservice infrastructure  | ~/.bashrc
| DOCKER_INFRASTRUCTURE_HOME       | <fully_qualified_path_to_docker-compose_direcotry>     | points to the directory where the __docker-ccompose.yml__ is located   | ~/.bashrc
|==============================

# Preparations
This sections deals with the preparations for the docker infrastructure. +

- Set environment variable __DOCKER_INFRASTRUCTURE_HOME__ in __.bashrc__ to point to __docker-compose.yml__ direcotry
- Set environment variable __RPISEC_VERSION__ in __.bashrc__ to define application version
- Create volume directories defined by the __.env__ contained environment variables in the docker executing user's home
- Define the configuration file __app.properties__ and place it in the directory defined by the environment variable __APP_CONF_VOLUME__
- Define the configuration file __auth.properties__ and place it in the directory defined by the environment variable __AUTH_CONF_VOLUME__
- Get firebase configuration file __firebase-account.json__ from firebase console and place it in the directory defined by the environment variable __APP_CONF_VOLUME__
- Get firebase configuration file __firebase-account.json__ from firebase console and place it in the directory defined by the environment variable __AUTH_CONF_VOLUME__
- Place a private and public certificate __(privatekey.pem, cert.pem)__ in the directory defined by the environment variable __NGINX_CERT_VOLUME__
- Create the __rpisec-base__ image via `./util.sh rebuildRpisecBase` in the directory __*/host/docker__ +
  __This could take a while because the raspberry pi binary sources are cloned from git and build for the specific environment__

# First start
This section deals with the first start of the docker infrastructure. +
Therefore that the databases are created the first time and the __postgres__ images return ok state in the meaning of docker, but do create
the database afterwards, it could be that the __rpisec-app__ and __rpisec-auth__ service fail because the databases are not ready. +
This could only occur when the database are getting initialized the first time, so restart the infrastructure and everything will work.

# Start stop infrastructure
This section deals with the starting and stopping of the dpcker infrastructure. All of the docker commands should be executed in the directory where the _docker-compose.yml__ resides, or
you need to specifiy the `-f path/docker-compose.yml` flag on each execution of an _docker-compose_ command. +
[options="header"]
|==============================
| Command                  | Performed action
| `docker-compose up`      | Creates the containers if necesarry and starts the services
| `docker-compose down`    | Stops the service and removes the related containers
| `docker-compose start`   | Starts the services with the existing containers
| `docker-compose stop`    | Stops the running services and keeps the containers
| `docker-compose restart` | Stops the running services if necesarry and starts them
|==============================
