Raspberry PI 3 security application
===================================
Thomas Herzog <herzog.thomas81@gmail.com>
v0.1, 2017/04/28, Initial intention description.

# App server
The app server is a spring boot application which manages the sensor application and
reports incidents to the registered clients and pushes the taken images to the firebase
database. +

link:rpisec-app/README.adoc[App server documentation] +

# Authentication server
The authentication server manages the domain users provides the oauth authentication mechanism
for the clients for accessing the app server. The registered client devices and firebase cloud messaging tokens
are pushed to the apps server, so that the app server is able to notify the clients about security incidents.

link:rpisec-oauth/README.adoc[Authentication server documentation] +

# Sensor application
The sensor application is a plain java implementation which manages and is hosted by the app server. +

link:rpisec-sensor/README.adoc[Sensor application documentation] +

# Docker infrastructure
The docker infrastructure documentation which hosts defines the services which host the applications and related services such as the reverse proxy and databases . +

link:host/docker/README.adoc[Docker infrastructure documentation] +
