Spring Boot application
=======================
Thomas Herzog <herzog.thomas81@gmail.com>

This document describes the usage of this application and how to set it up in an development and productive environment.

# Description
The spring boot application hosts the sensor application which interacts with the
raspberry pi hardware and notifies registered observers in an case of an security incident. +
The application registers such an observer and notifies registered user client devices
about an incident via an firebase cloud message and stores the taken snapshot image on the disk and the firebase
json database.

# Setup
This section deals with the setup of the spring boot application. +
The application supports two profiles __dev__ for __development__ environment and __prod__ for the __production__ environment
where the __productive__ environment is hosted within a docker infrastructure and the __development__ environment
works as a standalone application, where in the __development__ environment no sensor application will be necessary.

## Externalized configuration
The configuration has been split to a static part which is packaged into the application
and a dynamic part which is provided via the configuration file  __app-external-application.properties__. +
An template for the configuration file __app-external-application.properties__
can be found link:../../host/config/app-external-application.properties[here]. +

Firebase needs a configuration file named __firebase-account.json__ which can be downloaded
from the firebase console and must be keep private.

## Development Environment __(profile dev)__
This section deals with the necessary setup for the development environment.

### VM Options
The following VM options need to be set to get the application running via gradle.
[options="header"]
|======================
|Option                    | Values      | Usage
|-Dplatform                |  dev, prod  | Activates either dev or prod configurations
|-Dspring.config.location  | file:<path_to_file>/<config_file_name>.properties | Includes the externalized configuration
|======================

### Externalized Configuration
The externalized configuration file can be named and located as intended and will be
defined via an VM option as mentioned in the former section.

### Firebase
The __app-external-application.properties__ file must contain the parameter __firebase.configFile__ which defines
the location and name of the firebase configuration file. +

## Productive Environment
This section deals with the necessary setup for the productive environment. +
The productive environment is hosted in a docker infrastructure which is defined
via a docker-compose.yml which can be found link:../../host/docker/docker-compose.yml[here]. +

This application requires the following environment variables which are used in the __docker-compose.yml__ file and
most of them are already defined in the __.env__ file which can be found  link:../../host/docker/.env[here].

[options="header"]
|==============================
| Variable             | Value                       | Usage                                                   | Location
| APP_APP_VOLUME       | ~/docker-volumes/app/app    | mapped volume for the rpisec-app jars                   | .env
| APP_CONF_VOLUME      | ~/docker-volumes/app/conf   | mapped volume for the rpisec-app configurations         | .env
| APP_LOG_VOLUME       | ~/docker-volumes/app/log    | mapped volume for the rpisec-app logs                   | .env
| APP_IMAGE_VOLUME     | ~/docker-volumes/app/image  | mapped volume for the rpisec-app incident images        | .env
| APP_DB_VOLUME        | ~/docker-volumes/app/db     | mapped volume for the rpisec-app database               | .env
| RPISEC_VERSION       | 0.0.1-SNAPSHOT              | the current version of the microservice infrastructure  | ~/.bashrc
|==============================

### Externalized Configuration
The externalized configuration file must be named __app-external-application.properties__
and must be located at the root of the mapped conf volume defined by the environment variable __APP_CONF_VOLUME__.

### Firebase
The firebase configuration file must be named __firebase-account.json__ and must be located
at the root of the mapped conf volume defined by the environment variable __APP_CONF_VOLUME__.

# REST-API
TODO
